language: node_js 
node_js: stable 
install:
    - npm install 
script:
    - hexo clean 
    - hexo g 
after_script:
    - cd ./public
    - git init
    - git config user.name "DEBUG" 
    - git config user.email "465298643@qq.com" 
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${BLOG_TOKEN}@${GH_REF}" master:gh-pages 
branches:
    only:
        - master 
env:
    global:
        - GH_REF: github.com/DemoorBug/blog.git 